### PR TITLE
chore: remove unneeded devDependencies

### PR DESCRIPTION
**Pull request by XhmikosR**
These are inherited from the `@netlify/eslint-config-node`

Unsure about husky, but it's also included in `@netlify/eslint-config-node`

### CODE REVIEW

**Comment by erezrokah** [comment]
> Unsure about husky, but it's also included in `@netlify/eslint-config-node`

We tried removing `husky` in the past but we realized it's needed as a direct dependency. See https://github.com/netlify/zip-it-and-ship-it/pull/333

However, I tested it again and it works, so we can move forward with this.

**Comment by XhmikosR** [comment]
Your call, I can revert the husky removal if you prefer to play it safe (it doesn't really cost anything since it's being deduplicated).

**Review by erezrokah — APPROVED** [review]
🎸

**Comment by erezrokah** [comment]
> it doesn't really cost anything

It has the benefit of less renovate PRs to manage for this repo.

**Pull request merged**
